#!/usr/bin/env bash
#Transfer a file from client to server using scp

#check if 4 arguments are provided 
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi 

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file 
scp -i "$SSH_KEY" -o StrcitHostKeyChallenge=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
