#!/usr/bin/env bash
#install and configure Nginx on a new Ubuntu server

# Update package list and install nginx
apt-get update -y
apt-get install -y nginx

# Replace default page with our content
echo "Holberton School" > /var/www/html/index.html

# Restart Nginx using service
service nginx start || service nginx restart
